name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # jalan otomatis tiap tengah malam UTC
  workflow_dispatch: {}     # supaya bisa dijalankan manual dari tab Actions
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Generate 3D contribution SVGs
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ahmadsetiawande

      - name: Deploy to output-3d branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output-3d
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
